######################################################################
# Automatically generated by qmake (3.0) ons juli 8 16:26:59 2015
######################################################################

TEMPLATE = app
TARGET = c3
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h text_entry.h
SOURCES += main.cpp MainWindow.cpp
QT += widgets
QT += network
